# Generated by Django 4.1.4 on 2022-12-21 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=40)),
                ('application_portal', models.CharField(choices=[('Linkedin', 'Linkedin'), ('Company Website', 'Company Website'), ('Referral', 'Referral'), ('Job Search Site', 'Job Search Site')], max_length=50)),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('interviewed', models.BooleanField(blank=True, null=True)),
                ('final_feedback', models.BooleanField(blank=True, null=True)),
                ('spam', models.BooleanField(default=False)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
