# Generated by Django 4.1.4 on 2022-12-22 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_jobapplications_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplications',
            name='application_date',
            field=models.DateField(default=datetime.date(2022, 12, 22)),
        ),
    ]
