# Generated by Django 4.1.4 on 2022-12-23 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_jobapplications_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplications',
            name='application_date',
            field=models.DateField(default=datetime.date(2022, 12, 23)),
        ),
    ]
