# Generated by Django 4.1.4 on 2022-12-29 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_jobapplications_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='application_date',
            field=models.DateField(default=datetime.date(2022, 12, 29)),
        ),
        migrations.AlterField(
            model_name='jobapplications',
            name='application_portal',
            field=models.CharField(choices=[('Linkedin', 'Linkedin'), ('Company Website', 'Company Website'), ('Referral', 'Referral'), ('Job Search Site', 'Job Search Site'), ('Recruiter Call', 'Recruiter Call')], max_length=50),
        ),
    ]
