# Generated by Django 4.1.4 on 2022-12-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_jobapplications_application_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='spam',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
