# Generated by Django 4.1.4 on 2022-12-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_jobapplications_spam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
