# Generated by Django 4.1.4 on 2022-12-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_jobapplications_application_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='final_feedback',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplications',
            name='interviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
