# Generated by Django 4.1.4 on 2023-01-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_jobapplications_interviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
