# Generated by Django 4.1.4 on 2023-01-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_jobapplications_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('number_entries', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='entries',
            field=models.IntegerField(default=0),
        ),
    ]
