# Generated by Django 4.1.4 on 2023-01-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_entries_jobapplications_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='jobapplications',
            name='application_portal',
            field=models.CharField(choices=[('Linkedin', 'Linkedin'), ('Company Website', 'Company Website'), ('Referral', 'Referral'), ('Job Search Site', 'Job Search Site'), ('Recruiter Call', 'Recruiter Call'), ('Sent an email', 'Sent an email')], max_length=50),
        ),
    ]
