# Generated by Django 4.1.4 on 2023-01-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_importantlinks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
